# Generated by Django 2.1.1 on 2018-10-31 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 31, 7, 19, 37, 659726)),
        ),
    ]
