# Generated by Django 2.1.2 on 2018-10-31 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 19, 30, 58, 248561), verbose_name='Due'),
        ),
    ]
