# Generated by Django 2.1.1 on 2018-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
